version: '3.1'
services:

  db:
   container_name: edspace-db
   image: postgres
   environment:
    - POSTGRES_PASSWORD=edspace
    - POSTGRES_USER=edspace
    - POSTGRES_DB=edspace-db
   ports:
   - "5431:5432"
   restart: always

  web:
    container_name: edspace-web
    image: mirirous/edspace:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - db

